/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import static com.itextpdf.text.pdf.PdfName.FONT;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ClienteDAO;
import modelo.Detalle;
import modelo.Productos;
import modelo.ProductosDAO;
import modelo.Venta;
import modelo.VentaDAO;
import modelo.cliente;
import reportes.Excel;
/**
 *
 * @author Mariano Cuevas
 */
public class Sistema extends javax.swing.JFrame {
    int item;
    double Totalpagar= 0.00;
    cliente cl = new cliente();
    ClienteDAO cliente = new ClienteDAO();
    Productos pro = new Productos();
    ProductosDAO proDAO = new ProductosDAO();
    Venta venta = new Venta();
    VentaDAO ventaDAO = new VentaDAO();
    Detalle Dv = new Detalle();
    DefaultTableModel modelo = new DefaultTableModel();
    
    public Sistema() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtIdCliente.setVisible(false);
        txtIDStock.setVisible(false);
        txtIdVentas.setVisible(false);
        
    }
    //metodos varios:
public void ListarCliente(){
  List<cliente> listaCl = cliente.listarClientes();
  modelo = (DefaultTableModel) TablaCliente.getModel();
        Object[] ob = new Object[5];
        for (int i = 0; i < listaCl.size(); i++) {
            ob[0] = listaCl.get(i).getId();
            ob[1] = listaCl.get(i).getDni();
            ob[2] = listaCl.get(i).getNombre();
            ob[3] = listaCl.get(i).getTelefono();
            ob[4] = listaCl.get(i).getDireccion();
            modelo.addRow(ob);
        }
        TablaCliente.setModel(modelo);
   
}
public void LimpiarTabla(){
    for (int i=0; i<modelo.getRowCount(); i++){
       modelo.removeRow(i);
       i=i-1;
    }
}
private void LimpiarCliente(){
   txtIdCliente.setText("");
   txtDNICliente.setText("");
   txtNombreCliente.setText("");
   txtTelefonoCliente.setText("");
   txtDireccionCliente.setText("");
}
private void LimpiarProducto(){
   txtIDStock.setText("");
   txtNombreStock.setText("");
   txtStockStock.setText("");
   txtPrecioCompraStock.setText("");
   txtPrecioVentaStock.setText("");
   txtCodigoStock.setText("");
}
public void ListarProductos() {
    ProductosDAO proDAO = new ProductosDAO();
    List<Productos> listaPro = proDAO.listarProductos();
    DefaultTableModel modelo = (DefaultTableModel) TableStock.getModel();  // Asegúrate de que TableStock sea tu JTable para productos
    modelo.setRowCount(0); // Limpiar la tabla antes de agregar filas
    Object[] ob = new Object[6];  // Ajuste según el número de columnas de la tabla
    for (int i = 0; i < listaPro.size(); i++) {
        ob[0] = listaPro.get(i).getId();
        ob[1] = listaPro.get(i).getNombre();
        ob[2] = listaPro.get(i).getStock();
        ob[3] = listaPro.get(i).getPrecompra();
        ob[4] = listaPro.get(i).getPreventa();
        ob[5] = listaPro.get(i).getCodigo();
        modelo.addRow(ob);
    }
    TableStock.setModel(modelo);
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnStock = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtStockVentanva = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableVentanva = new javax.swing.JTable();
        btnEliminarVentanva = new javax.swing.JButton();
        txtPrecioVentanva = new javax.swing.JTextField();
        txtCantidadVentanva = new javax.swing.JTextField();
        txtCodigoVenta = new javax.swing.JTextField();
        btnImprimirVentanva = new javax.swing.JButton();
        txtNombreVentanva = new javax.swing.JTextField();
        txtDNIVentanva = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LabelTotal = new javax.swing.JLabel();
        txtTelefonoClienteVentanva = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtNomProVentanva = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtDireVentanva = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtDNICliente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        txtTelefonoCliente = new javax.swing.JTextField();
        txtDireccionCliente = new javax.swing.JTextField();
        btnGuardarCliente = new javax.swing.JButton();
        btnActualizarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        btnAgregarCliente = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaCliente = new javax.swing.JTable();
        txtIdCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtNombreStock = new javax.swing.JTextField();
        txtStockStock = new javax.swing.JTextField();
        txtPrecioCompraStock = new javax.swing.JTextField();
        txtPrecioVentaStock = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableStock = new javax.swing.JTable();
        txtCodigoStock = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnGuardarStock = new javax.swing.JButton();
        btnActualizarStock = new javax.swing.JButton();
        btnBorrarStock = new javax.swing.JButton();
        btnAgregarStock = new javax.swing.JButton();
        btnExcelStock = new javax.swing.JButton();
        txtIDStock = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableVentas = new javax.swing.JTable();
        btnPDFVentas = new javax.swing.JButton();
        txtIdVentas = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Clientes.png"))); // NOI18N
        jButton1.setText("Cliente");
        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(129, 33));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nventa.png"))); // NOI18N
        jButton6.setText("Nueva Venta");
        jButton6.setBorder(null);
        jButton6.setPreferredSize(new java.awt.Dimension(129, 33));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        btnStock.setText("Stock");
        btnStock.setBorder(null);
        btnStock.setPreferredSize(new java.awt.Dimension(129, 33));
        btnStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/compras.png"))); // NOI18N
        jButton3.setText("Ventas");
        jButton3.setBorder(null);
        jButton3.setPreferredSize(new java.awt.Dimension(129, 33));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/config.png"))); // NOI18N
        jButton7.setText("Config");
        jButton7.setBorder(null);
        jButton7.setPreferredSize(new java.awt.Dimension(129, 33));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo copado.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(btnStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStock, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 640));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 320, 120));

        jLabel8.setText("Codigo");

        jLabel11.setText("Cantidad");

        jLabel12.setText("Precio");

        jLabel13.setText("Stock");

        TableVentanva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane1.setViewportView(TableVentanva);
        if (TableVentanva.getColumnModel().getColumnCount() > 0) {
            TableVentanva.getColumnModel().getColumn(0).setPreferredWidth(50);
            TableVentanva.getColumnModel().getColumn(1).setPreferredWidth(50);
            TableVentanva.getColumnModel().getColumn(2).setPreferredWidth(30);
            TableVentanva.getColumnModel().getColumn(3).setPreferredWidth(50);
            TableVentanva.getColumnModel().getColumn(4).setPreferredWidth(30);
        }

        btnEliminarVentanva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btnEliminarVentanva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVentanvaActionPerformed(evt);
            }
        });

        txtPrecioVentanva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioVentanvaActionPerformed(evt);
            }
        });

        txtCantidadVentanva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadVentanvaKeyPressed(evt);
            }
        });

        txtCodigoVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoVentaKeyPressed(evt);
            }
        });

        btnImprimirVentanva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print.png"))); // NOI18N
        btnImprimirVentanva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirVentanvaActionPerformed(evt);
            }
        });

        txtNombreVentanva.setEditable(false);
        txtNombreVentanva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreVentanvaActionPerformed(evt);
            }
        });

        txtDNIVentanva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIVentanvaActionPerformed(evt);
            }
        });
        txtDNIVentanva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDNIVentanvaKeyPressed(evt);
            }
        });

        jLabel20.setText("DNI");

        jLabel9.setText("Nombre");

        jLabel6.setText("Total a pagar : ");

        LabelTotal.setText("...................");

        txtTelefonoClienteVentanva.setEditable(false);
        txtTelefonoClienteVentanva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoClienteVentanvaActionPerformed(evt);
            }
        });

        jLabel14.setText("Telefono");

        jLabel32.setText("Producto");

        jLabel33.setText("Direccion");

        txtDireVentanva.setEditable(false);
        txtDireVentanva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireVentanvaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel9)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel14)
                        .addGap(309, 309, 309))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel8)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel32)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel11)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel12)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel13))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txtCodigoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNomProVentanva, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCantidadVentanva, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrecioVentanva, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtStockVentanva, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarVentanva))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtDNIVentanva, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNombreVentanva, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTelefonoClienteVentanva, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel33))
                                    .addComponent(txtDireVentanva, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(btnImprimirVentanva, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addGap(441, 441, 441))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel32))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCantidadVentanva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPrecioVentanva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtStockVentanva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNomProVentanva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEliminarVentanva, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDNIVentanva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreVentanva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefonoClienteVentanva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33)
                        .addGap(10, 10, 10)
                        .addComponent(txtDireVentanva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(LabelTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImprimirVentanva, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nueva Venta", jPanel2);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("DNI :");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel17.setText("Nombre :");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel18.setText("Telefono :");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel19.setText("Direccion:");

        txtDNICliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIClienteActionPerformed(evt);
            }
        });

        txtTelefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoClienteActionPerformed(evt);
            }
        });

        btnGuardarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/GuardarTodo.png"))); // NOI18N
        btnGuardarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarCliente.setMaximumSize(new java.awt.Dimension(35, 35));
        btnGuardarCliente.setMinimumSize(new java.awt.Dimension(35, 35));
        btnGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClienteActionPerformed(evt);
            }
        });

        btnActualizarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actualizar (2).png"))); // NOI18N
        btnActualizarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarCliente.setMaximumSize(new java.awt.Dimension(35, 35));
        btnActualizarCliente.setMinimumSize(new java.awt.Dimension(35, 35));
        btnActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarClienteActionPerformed(evt);
            }
        });

        btnEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar.png"))); // NOI18N
        btnEliminarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarCliente.setMaximumSize(new java.awt.Dimension(35, 35));
        btnEliminarCliente.setMinimumSize(new java.awt.Dimension(35, 35));
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });

        btnAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        btnAgregarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarCliente.setMaximumSize(new java.awt.Dimension(35, 35));
        btnAgregarCliente.setMinimumSize(new java.awt.Dimension(35, 35));
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });

        TablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DNI", "Nombre", "Telefono", "Direccion"
            }
        ));
        TablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaClienteMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TablaCliente);
        if (TablaCliente.getColumnModel().getColumnCount() > 0) {
            TablaCliente.getColumnModel().getColumn(1).setPreferredWidth(100);
            TablaCliente.getColumnModel().getColumn(2).setPreferredWidth(100);
            TablaCliente.getColumnModel().getColumn(3).setPreferredWidth(50);
            TablaCliente.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        txtIdCliente.setEditable(false);
        txtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Guardar");

        jLabel15.setText("Actualizar");

        jLabel26.setText("Nuevo");

        jLabel27.setText("Borrar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(14, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDNICliente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGuardarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnEliminarCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(btnActualizarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnAgregarCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtDNICliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(txtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnActualizarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel26))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(430, 800));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel10.setText("Nombre :");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel21.setText("Stock :");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel22.setText("Precio de compra :");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel23.setText("Precio de venta :");

        txtStockStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockStockActionPerformed(evt);
            }
        });

        txtPrecioCompraStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioCompraStockActionPerformed(evt);
            }
        });

        TableStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Stock", "Precio de compra", "Precio de venta", "Codigo"
            }
        ));
        TableStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableStockMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableStock);
        if (TableStock.getColumnModel().getColumnCount() > 0) {
            TableStock.getColumnModel().getColumn(0).setPreferredWidth(30);
            TableStock.getColumnModel().getColumn(1).setPreferredWidth(100);
            TableStock.getColumnModel().getColumn(2).setPreferredWidth(100);
            TableStock.getColumnModel().getColumn(3).setPreferredWidth(50);
            TableStock.getColumnModel().getColumn(4).setPreferredWidth(50);
            TableStock.getColumnModel().getColumn(5).setPreferredWidth(50);
        }

        jLabel24.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel24.setText("Codigo :");

        btnGuardarStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/GuardarTodo.png"))); // NOI18N
        btnGuardarStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarStockActionPerformed(evt);
            }
        });

        btnActualizarStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actualizar (2).png"))); // NOI18N
        btnActualizarStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarStockActionPerformed(evt);
            }
        });

        btnBorrarStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar.png"))); // NOI18N
        btnBorrarStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarStockActionPerformed(evt);
            }
        });

        btnAgregarStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        btnAgregarStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarStockMouseClicked(evt);
            }
        });
        btnAgregarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarStockActionPerformed(evt);
            }
        });

        btnExcelStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excel.png"))); // NOI18N
        btnExcelStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcelStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelStockActionPerformed(evt);
            }
        });

        jLabel28.setText("Guardar");

        jLabel29.setText("Actualizar");

        jLabel30.setText("Borrar");

        jLabel31.setText("Nuevo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnExcelStock, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(btnGuardarStock))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAgregarStock)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel30))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(btnActualizarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(btnBorrarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel31)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreStock, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPrecioVentaStock, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCodigoStock, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPrecioCompraStock, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtStockStock, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDStock, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtNombreStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStockStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecioCompraStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txtPrecioVentaStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIDStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrarStock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcelStock)
                    .addComponent(btnAgregarStock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Stock", jPanel5);

        TableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Cliente", "Producto", "Cantidad", "Suma total"
            }
        ));
        jScrollPane4.setViewportView(TableVentas);
        if (TableVentas.getColumnModel().getColumnCount() > 0) {
            TableVentas.getColumnModel().getColumn(0).setPreferredWidth(50);
            TableVentas.getColumnModel().getColumn(1).setPreferredWidth(100);
            TableVentas.getColumnModel().getColumn(2).setPreferredWidth(100);
            TableVentas.getColumnModel().getColumn(3).setPreferredWidth(50);
            TableVentas.getColumnModel().getColumn(4).setPreferredWidth(80);
        }

        btnPDFVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdf.png"))); // NOI18N
        btnPDFVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnPDFVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPDFVentas)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtIdVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ventas", jPanel6);

        jLabel4.setText("Nombre");

        jLabel5.setText("Direccion");

        jLabel7.setText("Telefono");

        jLabel25.setText("jLabel25");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel25))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel7))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(690, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(73, 73, 73)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        jTabbedPane1.addTab("Config", jPanel7);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 1010, 430));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 880, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private javax.swing.JTable tablaClientes;
    //metodos de botones:
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LimpiarTabla();
        ListarCliente();
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockActionPerformed
        // TODO add your handling code here:
        LimpiarTabla();
        ListarProductos();
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnStockActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtTelefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoClienteActionPerformed

    private void btnActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarClienteActionPerformed
    // Verifica si el campo de ID del cliente está vacío
    if ("".equals(txtIdCliente.getText())) {
        JOptionPane.showMessageDialog(null, "Seleccione una fila");
    } else {
        // Verifica si todos los campos necesarios están llenos
        if (!"".equals(txtDNICliente.getText()) && !"".equals(txtNombreCliente.getText())
                && !"".equals(txtTelefonoCliente.getText()) && !"".equals(txtDireccionCliente.getText())) {
            try {
                // Setea los valores del cliente
                cl.setDni(Integer.parseInt(txtDNICliente.getText()));
                cl.setNombre(txtNombreCliente.getText());
                cl.setTelefono(txtTelefonoCliente.getText());
                cl.setDireccion(txtDireccionCliente.getText());
                cl.setId(Integer.parseInt(txtIdCliente.getText()));
                // Llama al método para modificar el cliente
                boolean actualizado = cliente.ModificarCliente(cl);
                if (actualizado) {
                    JOptionPane.showMessageDialog(null, "Cliente actualizado correctamente");
                    LimpiarTabla();
                    LimpiarCliente();
                    ListarCliente();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al actualizar el cliente");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Error en el formato de los datos: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Los campos están vacíos");
        }
    }
    }//GEN-LAST:event_btnActualizarClienteActionPerformed

    private void btnGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClienteActionPerformed
    try {
        if (!"".equals(txtDNICliente.getText().trim()) && !"".equals(txtNombreCliente.getText().trim())
                && !"".equals(txtTelefonoCliente.getText().trim()) && !"".equals(txtDireccionCliente.getText().trim())) {

            int dni = Integer.parseInt(txtDNICliente.getText().trim());
            String telefonoStr = txtTelefonoCliente.getText().trim();
            
            // Validar que el teléfono tenga exactamente 10 dígitos y sea un número
            if (telefonoStr.length() != 10 || !telefonoStr.matches("\\d{10}")) {
                JOptionPane.showMessageDialog(null, "El teléfono debe tener exactamente 10 dígitos numéricos");
                return;
            }

            cl.setDni(dni);
            cl.setNombre(txtNombreCliente.getText().trim());
            cl.setTelefono(telefonoStr);
            cl.setDireccion(txtDireccionCliente.getText().trim());
            cliente.registrarCliente(cl);
            LimpiarTabla();
            LimpiarCliente();
            ListarCliente();
            JOptionPane.showMessageDialog(null, "Cliente registrado");
        } else {
            JOptionPane.showMessageDialog(null, "Todos los campos deben ser llenados");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "DNI debe ser un número válido");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Ocurrió un error al registrar el cliente: " + e.getMessage());
    }

    }//GEN-LAST:event_btnGuardarClienteActionPerformed

    private void txtPrecioCompraStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioCompraStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioCompraStockActionPerformed

    private void txtStockStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockStockActionPerformed

    private void btnGuardarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarStockActionPerformed
          try {
        if (!"".equals(txtNombreStock.getText()) && !"".equals(txtStockStock.getText()) && 
            !"".equals(txtPrecioCompraStock.getText()) && !"".equals(txtPrecioVentaStock.getText()) &&
            !"".equals(txtCodigoStock.getText())) {

            // Crear objeto de producto y asignar valores
            Productos pro = new Productos();
            pro.setNombre(txtNombreStock.getText());
            pro.setStock(Integer.parseInt(txtStockStock.getText()));
            pro.setPrecompra(Double.parseDouble(txtPrecioCompraStock.getText()));
            pro.setPreventa(Double.parseDouble(txtPrecioVentaStock.getText()));
            pro.setCodigo(txtCodigoStock.getText());

            // Registrar producto en la base de datos
            if (proDAO.RegistrarProducto(pro)) {
                JOptionPane.showMessageDialog(null, "Producto registrado exitosamente");
                ListarProductos();  // Actualizar la tabla después de agregar el producto
            } else {
                JOptionPane.showMessageDialog(null, "Error al registrar el producto");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Todos los campos deben ser llenados");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Stock, precio de compra y precio de venta deben ser números válidos");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Ocurrió un error al registrar el producto: " + e.getMessage());
    }           
        
        
    }//GEN-LAST:event_btnGuardarStockActionPerformed

    private void btnActualizarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarStockActionPerformed
        // TODO add your handling code here:
    // Verifica si el campo de ID del producto está vacío
    if ("".equals(txtIDStock.getText())) {
        JOptionPane.showMessageDialog(null, "Seleccione una fila");
    } else {
        // Verifica si todos los campos necesarios están llenos
        if (!"".equals(txtNombreStock.getText()) && !"".equals(txtStockStock.getText())
                && !"".equals(txtPrecioCompraStock.getText()) && !"".equals(txtPrecioVentaStock.getText())
                && !"".equals(txtCodigoStock.getText())) {
            try {
                // Setea los valores del producto
                Productos producto = new Productos();
                producto.setId(Integer.parseInt(txtIDStock.getText()));
                producto.setNombre(txtNombreStock.getText());
                producto.setStock(Integer.parseInt(txtStockStock.getText()));
                producto.setPrecompra(Double.parseDouble(txtPrecioCompraStock.getText()));
                producto.setPreventa(Double.parseDouble(txtPrecioVentaStock.getText()));
                producto.setCodigo(txtCodigoStock.getText());
                
                // Llama al método para modificar el producto
                ProductosDAO proDAO = new ProductosDAO();
                boolean actualizado = proDAO.modificarProducto(producto);
                if (actualizado) {
                    JOptionPane.showMessageDialog(null, "Producto actualizado correctamente");
                    LimpiarTabla();
                    LimpiarProducto();
                    ListarProductos();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al actualizar el producto");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Error en el formato de los datos: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Los campos están vacíos");
        }
    }
    }//GEN-LAST:event_btnActualizarStockActionPerformed

    private void btnPDFVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPDFVentasActionPerformed

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdClienteActionPerformed

    private void txtDNIClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIClienteActionPerformed

    private void TablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaClienteMouseClicked
     int fila= TablaCliente.rowAtPoint(evt.getPoint());
     txtIdCliente.setText(TablaCliente.getValueAt(fila,0).toString());
     txtDNICliente.setText(TablaCliente.getValueAt(fila,1).toString());
     txtNombreCliente.setText(TablaCliente.getValueAt(fila,2).toString());
     txtTelefonoCliente.setText(TablaCliente.getValueAt(fila,3).toString());
     txtDireccionCliente.setText(TablaCliente.getValueAt(fila,4).toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_TablaClienteMouseClicked

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        // TODO add your handling code here:
   if (!"".equals(txtIdCliente.getText().trim())) {
        int pregunta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de eliminar este cliente?");
        if (pregunta == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(txtIdCliente.getText().trim());
            ClienteDAO ClienteDAO = new ClienteDAO();
            boolean eliminado = ClienteDAO.EliminarCliente(id);
            if (eliminado) {
                JOptionPane.showMessageDialog(null, "Cliente eliminado");
                LimpiarTabla();
                LimpiarCliente();
                ListarCliente();
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar el cliente");
            }
        }
    } else {
        JOptionPane.showMessageDialog(null, "Ingrese un ID de cliente válido");
    }
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        // TODO add your handling code here:}
        LimpiarCliente();
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnBorrarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarStockActionPerformed
        // TODO add your handling code here:
          // Verifica si el campo de ID del producto no está vacío
    if (!"".equals(txtIDStock.getText().trim())) {
        int pregunta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de eliminar este producto?");
        if (pregunta == JOptionPane.YES_OPTION) {
            try {
                int id = Integer.parseInt(txtIDStock.getText().trim());
                
                // Instancia de ProductosDAO
                ProductosDAO proDAO = new ProductosDAO();
                
                // Intenta eliminar el producto
                boolean eliminado = proDAO.eliminarProducto(id);
                
                if (eliminado) {
                    JOptionPane.showMessageDialog(null, "Producto eliminado");
                    LimpiarTabla();
                    LimpiarProducto();
                    ListarProductos();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al eliminar el producto");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese un ID de producto válido");
            }
        }
    } else {
        JOptionPane.showMessageDialog(null, "Ingrese un ID de producto válido");
    }
    }//GEN-LAST:event_btnBorrarStockActionPerformed

    private void TableStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableStockMouseClicked
        // TODO add your handling code here:
        int fila= TableStock.rowAtPoint(evt.getPoint());
     txtIDStock.setText(TableStock.getValueAt(fila,0).toString());
     txtNombreStock.setText(TableStock.getValueAt(fila,1).toString());
     txtStockStock.setText(TableStock.getValueAt(fila,2).toString());
     txtPrecioCompraStock.setText(TableStock.getValueAt(fila,3).toString());
     txtPrecioVentaStock.setText(TableStock.getValueAt(fila,4).toString());
     txtCodigoStock.setText(TableStock.getValueAt(fila,5).toString());
    }//GEN-LAST:event_TableStockMouseClicked

    private void btnAgregarStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarStockMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarStockMouseClicked

    private void btnAgregarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarStockActionPerformed
      LimpiarProducto();
        
        
    }//GEN-LAST:event_btnAgregarStockActionPerformed

    private void btnExcelStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelStockActionPerformed
        // TODO add your handling code here:
        Excel.reporte();
    }//GEN-LAST:event_btnExcelStockActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtDireVentanvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireVentanvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireVentanvaActionPerformed

    private void txtTelefonoClienteVentanvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoClienteVentanvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoClienteVentanvaActionPerformed

    private void txtDNIVentanvaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIVentanvaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!"".equals(txtDNIVentanva.getText())) {
                try {
                    int dni = Integer.parseInt(txtDNIVentanva.getText());
                    cliente cl = cliente.BuscarCliente(dni);
                    if (cl != null && cl.getNombre() != null) {
                        txtNombreVentanva.setText(cl.getNombre());
                        txtTelefonoClienteVentanva.setText(cl.getTelefono());
                        txtDireVentanva.setText(cl.getDireccion());
                        txtDNIVentanva.requestFocus();
                    } else {
                        //  LimpiarCliNvaVenta();
                        txtDNIVentanva.requestFocus();
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Por favor ingrese un DNI válido.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Por favor ingrese el DNI de un cliente.");
            }
        }
    }//GEN-LAST:event_txtDNIVentanvaKeyPressed

    private void txtDNIVentanvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIVentanvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIVentanvaActionPerformed

    private void txtNombreVentanvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreVentanvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreVentanvaActionPerformed

    private void btnImprimirVentanvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirVentanvaActionPerformed
        // TODO add your handling code here:
        RegistrarVenta();
        RegistrarDetalle();
        ActualizarStock();
        pdf();
        LimpiarTableVenta();
    }//GEN-LAST:event_btnImprimirVentanvaActionPerformed

    private void txtCodigoVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoVentaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(!"".equals(txtCodigoVenta.getText())){
                String cod = txtCodigoVenta.getText();
                pro = proDAO.BuscarPro(cod);
                if(pro.getNombre()!=null){
                    txtNomProVentanva.setText(""+pro.getNombre());
                    txtPrecioVentanva.setText(String.valueOf(""+pro.getPreventa()));
                    txtStockVentanva.setText(String.valueOf(""+pro.getStock()));
                    txtCantidadVentanva.requestFocus();
                }else{
                    LimpiarNvaVenta();
                    txtCodigoVenta.requestFocus();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Por favor ingresa un código");}
        }
    }//GEN-LAST:event_txtCodigoVentaKeyPressed

    private void txtCantidadVentanvaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadVentanvaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if(!"".equals(txtCantidadVentanva.getText())) {
                try {
                    String cod = txtCodigoVenta.getText();
                    String producto = txtNomProVentanva.getText();
                    int cant = Integer.parseInt(txtCantidadVentanva.getText());
                    double precio = Double.parseDouble(txtPrecioVentanva.getText());
                    double total = cant * precio;
                    int stock = Integer.parseInt(txtStockVentanva.getText());

                    if(stock >= cant) {
                        modelo = (DefaultTableModel) TableVentanva.getModel();

                        for(int i = 0; i < modelo.getRowCount(); i++) {
                            if(modelo.getValueAt(i, 1).equals(producto)) {
                                JOptionPane.showMessageDialog(null, "El producto ya está registrado");
                                return;
                            }
                        }

                        item = item + 1;
                        ArrayList<Object> lista = new ArrayList<>();
                        lista.add(item);
                        lista.add(cod);
                        lista.add(producto);
                        lista.add(cant);
                        lista.add(precio);
                        lista.add(total);

                        Object[] O = new Object[5];
                        O[0] = lista.get(1);
                        O[1] = lista.get(2);
                        O[2] = lista.get(3);
                        O[3] = lista.get(4);
                        O[4] = lista.get(5);

                        modelo.addRow(O);
                        TableVentanva.setModel(modelo);
                        TotalPagar();
                        LimpiarNvaVenta();
                        txtCodigoVenta.requestFocus();

                        // Actualizar el stock
                        txtStockVentanva.setText(String.valueOf(stock - cant));
                    } else {
                        JOptionPane.showMessageDialog(null, "Stock no disponible");
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Ingrese valores válidos");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese cantidad");
            }
        }
    }//GEN-LAST:event_txtCantidadVentanvaKeyPressed

    private void txtPrecioVentanvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioVentanvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioVentanvaActionPerformed

    private void btnEliminarVentanvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVentanvaActionPerformed
        // Obtener el índice de la fila seleccionada
        int filaSeleccionada = TableVentanva.getSelectedRow();

        // Verificar si se ha seleccionado una fila
        if (filaSeleccionada == -1) {
            // No se ha seleccionado ninguna fila, mostrar un mensaje
            JOptionPane.showMessageDialog(null, "Por favor, seleccione una fila para eliminar.");
        } else {
            // Se ha seleccionado una fila, proceder a eliminarla
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Está seguro de que desea eliminar la venta seleccionada?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                // Eliminar la fila seleccionada del modelo de la tabla
                DefaultTableModel modelo = (DefaultTableModel) TableVentanva.getModel();
                modelo.removeRow(filaSeleccionada);

                // Mostrar un mensaje de éxito
                JOptionPane.showMessageDialog(null, "Venta eliminada correctamente.");

                // Actualizar el total a pagar
                TotalPagar();
                txtCodigoVenta.requestFocus();
            }
        }
    }//GEN-LAST:event_btnEliminarVentanvaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTotal;
    private javax.swing.JTable TablaCliente;
    private javax.swing.JTable TableStock;
    private javax.swing.JTable TableVentanva;
    private javax.swing.JTable TableVentas;
    private javax.swing.JButton btnActualizarCliente;
    private javax.swing.JButton btnActualizarStock;
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnAgregarStock;
    private javax.swing.JButton btnBorrarStock;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnEliminarVentanva;
    private javax.swing.JButton btnExcelStock;
    private javax.swing.JButton btnGuardarCliente;
    private javax.swing.JButton btnGuardarStock;
    private javax.swing.JButton btnImprimirVentanva;
    private javax.swing.JButton btnPDFVentas;
    private javax.swing.JButton btnStock;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txtCantidadVentanva;
    private javax.swing.JTextField txtCodigoStock;
    private javax.swing.JTextField txtCodigoVenta;
    private javax.swing.JTextField txtDNICliente;
    private javax.swing.JTextField txtDNIVentanva;
    private javax.swing.JTextField txtDireVentanva;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtIDStock;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdVentas;
    private javax.swing.JTextField txtNomProVentanva;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreStock;
    private javax.swing.JTextField txtNombreVentanva;
    private javax.swing.JTextField txtPrecioCompraStock;
    private javax.swing.JTextField txtPrecioVentaStock;
    private javax.swing.JTextField txtPrecioVentanva;
    private javax.swing.JTextField txtStockStock;
    private javax.swing.JTextField txtStockVentanva;
    private javax.swing.JTextField txtTelefonoCliente;
    private javax.swing.JTextField txtTelefonoClienteVentanva;
    // End of variables declaration//GEN-END:variables
private void TotalPagar() {
    Totalpagar = 0.00;
    int numFila = TableVentanva.getRowCount();
    for (int i = 0; i < numFila; i++) {
        double cal = Double.parseDouble(String.valueOf(TableVentanva.getModel().getValueAt(i, 4)));
        Totalpagar = Totalpagar + cal;
    }
    LabelTotal.setText(String.format("%.2f", Totalpagar));
}
private void LimpiarNvaVenta(){
   txtCodigoVenta.setText("");
   txtNomProVentanva.setText("");
   txtCantidadVentanva.setText("");
   txtPrecioVentanva.setText("");
   txtStockVentanva.setText("");
}
private void LimpiarCliNvaVenta(){
   txtDNIVentanva.setText("");
   txtNombreVentanva.setText("");
   txtTelefonoClienteVentanva.setText("");
   txtDireVentanva.setText("");
}
private void RegistrarVenta() {
    try {
        String cliente = txtNombreVentanva.getText();    
        double monto = Totalpagar;
        Venta v = new Venta();
        v.setCliente(cliente);
        v.setTotal(monto);
        VentaDAO ventaDAO = new VentaDAO();
        ventaDAO.RegistrarVenta(v);
        JOptionPane.showMessageDialog(null, "Venta registrada con éxito");
    } catch (NumberFormatException e) {
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Ocurrió un error al registrar la venta: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}
}
private void RegistrarDetalle(){
    for (int i=0; i<TableVentanva.getRowCount(); i++){
        String cod = TableVentanva.getValueAt(i, 0).toString();
        int cant = Integer.parseInt(TableVentanva.getValueAt(i, 2).toString());
        String producto = TableVentanva.getValueAt(i, 1).toString();
        double precio = Double.parseDouble(TableVentanva.getValueAt(i, 3).toString());
        Detalle Dv = new Detalle();
        Dv.setCodigo(cod);
        Dv.setCantidad(cant);
        Dv.setProducto(producto);
        Dv.setPrecio(precio);
        ventaDAO.RegistrarDetalle(Dv);
    } 
}
private void ActualizarStock(){
  for (int i=0; i<TableVentanva.getRowCount(); i++){
        String cod = TableVentanva.getValueAt(i, 0).toString();
        int cant = Integer.parseInt(TableVentanva.getValueAt(i, 2).toString());
        pro = proDAO.BuscarPro(cod);
        int StockActual = pro.getStock() - cant;
        ventaDAO.ActualizarStock(StockActual, cod);
    } 
}
private void LimpiarTableVenta() {
    DefaultTableModel tmp = (DefaultTableModel) TableVentanva.getModel();
    int fila = TableVentanva.getRowCount();
    for (int i = fila - 1; i >= 0; i--) {
        tmp.removeRow(0);
    }
}
private void pdf(){
    try{
        Date date = new Date();
        FileOutputStream archivo;
        File file = new File("src/PDF/venta.pdf");
        archivo = new FileOutputStream(file);
        Document doc = new Document();
        PdfWriter.getInstance(doc, archivo);
        doc.open();
        Image img = Image.getInstance("src/img/Logo copado.png");
        Paragraph fecha = new Paragraph();
        Font negrita = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD, BaseColor.BLACK);
        fecha.add(Chunk.NEWLINE);
        fecha.add("Fecha: "+ new SimpleDateFormat("dd-MM-yy").format(date)+"\n\n");
        PdfPTable Encabezado= new PdfPTable(4);
        Encabezado.setWidthPercentage(100);
        Encabezado.getDefaultCell().setBorder(0);
        float [] ColumnaEncabezado = new float[]{20f,30f,70f,40f};
        Encabezado.setWidths(ColumnaEncabezado);
        Encabezado.setHorizontalAlignment(Element.ALIGN_CENTER);
        Encabezado.addCell(img);
        String dni="24746128";
        String nomb="Atelier Susana Battoia";
        String tel="2995352465";
        String dire="Praga 444 Catriel Rio Negro";
        Encabezado.addCell("");
        Encabezado.addCell("DNI: " + dni + "\nNombre: " + nomb + "\nTelefono: " + tel + "\nDireccion: " + dire);
        Encabezado.addCell(fecha);
        doc.add(Encabezado);
        Paragraph cli= new Paragraph();
        cli.add(Chunk.NEWLINE);
        cli.add("Datos de los clientes"+"\n\n");
        doc.add(cli);
        PdfPTable tablacli= new PdfPTable(4);
        tablacli.setWidthPercentage(100);
        tablacli.getDefaultCell().setBorder(0);
        float [] Columnacli = new float[]{20f,30f,70f,40f};
        tablacli.setWidths(Columnacli);
        tablacli.setHorizontalAlignment(Element.ALIGN_LEFT);
        PdfPCell cl1 = new PdfPCell (new Phrase("DNI", negrita));
        PdfPCell cl2 = new PdfPCell (new Phrase("Nombre", negrita));
        PdfPCell cl3 = new PdfPCell (new Phrase("Telefono", negrita));
        PdfPCell cl4 = new PdfPCell (new Phrase("Direccion", negrita));
        cl1.setBorder(0);
        cl2.setBorder(0);
        cl3.setBorder(0);
        cl4.setBorder(0);
        cl1.setBackgroundColor(BaseColor.LIGHT_GRAY);
        cl2.setBackgroundColor(BaseColor.LIGHT_GRAY);
        cl3.setBackgroundColor(BaseColor.LIGHT_GRAY);
        cl4.setBackgroundColor(BaseColor.LIGHT_GRAY);
        tablacli.addCell(cl1);
        tablacli.addCell(cl2);
        tablacli.addCell(cl3);
        tablacli.addCell(cl4);
        tablacli.addCell(txtDNIVentanva.getText());
        tablacli.addCell(txtNombreVentanva.getText());
        tablacli.addCell(txtTelefonoClienteVentanva.getText());
        tablacli.addCell(txtDireVentanva.getText());
        doc.add(tablacli);
        //productos
        PdfPTable tablapro = new PdfPTable(4);
        tablapro.setWidthPercentage(100);
        tablapro.getDefaultCell().setBorder(0);
        float [] Columnapro = new float[]{20f,15f,15f,20f};
        tablapro.setWidths(Columnapro);
        tablapro.setHorizontalAlignment(Element.ALIGN_LEFT);
        PdfPCell pro1 = new PdfPCell (new Phrase("Producto", negrita));
        PdfPCell pro2 = new PdfPCell (new Phrase("Precio unidad", negrita));
        PdfPCell pro3 = new PdfPCell (new Phrase("Cantidad", negrita));
        PdfPCell pro4 = new PdfPCell (new Phrase("Precio total", negrita));
        pro1.setBorder(0);
        pro2.setBorder(0);
        pro3.setBorder(0);
        pro4.setBorder(0);
        pro1.setBackgroundColor(BaseColor.LIGHT_GRAY);
        pro2.setBackgroundColor(BaseColor.LIGHT_GRAY);
        pro3.setBackgroundColor(BaseColor.LIGHT_GRAY);
        pro4.setBackgroundColor(BaseColor.LIGHT_GRAY);
        tablapro.addCell(pro1);
        tablapro.addCell(pro2);
        tablapro.addCell(pro3);
        tablapro.addCell(pro4);
        for(int i=0; i<TableVentanva.getRowCount(); i++){
        String producto = TableVentanva.getValueAt(i, 1).toString();
        String precio = TableVentanva.getValueAt(i, 3).toString();
        String cantidad= TableVentanva.getValueAt(i, 2).toString();
        String total = TableVentanva.getValueAt(i, 4).toString();
        tablapro.addCell(producto);
        tablapro.addCell(precio);
        tablapro.addCell(cantidad);
        tablapro.addCell(total);
        }
          doc.add(tablapro);
          Paragraph info = new Paragraph();
          info.add(Chunk.NEWLINE);
          info.add("Total a pagar: "+ Totalpagar);
          info.setAlignment(Element.ALIGN_RIGHT);
          doc.add(info);
        /*  Paragraph firma = new Paragraph();
          info.add(Chunk.NEWLINE);
          info.add("Cancelacion y firma\n\n");
          info.add("..........................");
          info.setAlignment(Element.ALIGN_CENTER);
          doc.add(info);
          Paragraph Mensaje = new Paragraph();
          info.add(Chunk.NEWLINE);
          info.add("Gracias por su compra");
          info.setAlignment(Element.ALIGN_CENTER);
          doc.add(info);*/
          doc.close();
          archivo.close();
          Desktop.getDesktop().open(file);
}catch(DocumentException | IOException e){
System.out.println(e.toString());
}
}

}





